// Code generated by Microsoft (R) TypeSpec Code Generator.

module com.openai {
    requires transitive io.clientcore.core;
    requires transitive io.clientcore.core.json;
    exports com.openai;
    exports com.openai.models;
    opens com.openai.models to io.clientcore.core;
}