// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.openai.models;

import io.clientcore.core.annotation.Metadata;
import io.clientcore.core.annotation.TypeConditions;
import io.clientcore.core.json.JsonReader;
import io.clientcore.core.json.JsonSerializable;
import io.clientcore.core.json.JsonToken;
import io.clientcore.core.json.JsonWriter;
import java.io.IOException;

/**
 * The AssistantToolsRetrieval model.
 */
@Metadata(conditions = { TypeConditions.IMMUTABLE })
public final class AssistantToolsRetrieval implements JsonSerializable<AssistantToolsRetrieval> {
    /*
     * The type of tool being defined: `retrieval`
     */
    @Metadata(generated = true)
    private final String type = "retrieval";

    /**
     * Creates an instance of AssistantToolsRetrieval class.
     */
    @Metadata(generated = true)
    public AssistantToolsRetrieval() {
    }

    /**
     * Get the type property: The type of tool being defined: `retrieval`.
     * 
     * @return the type value.
     */
    @Metadata(generated = true)
    public String getType() {
        return this.type;
    }

    /**
     * {@inheritDoc}
     */
    @Metadata(generated = true)
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeStringField("type", this.type);
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of AssistantToolsRetrieval from the JsonReader.
     * 
     * @param jsonReader The JsonReader being read.
     * @return An instance of AssistantToolsRetrieval if the JsonReader was pointing to an instance of it, or null if it
     * was pointing to JSON null.
     * @throws IllegalStateException If the deserialized JSON object was missing any required properties.
     * @throws IOException If an error occurs while reading the AssistantToolsRetrieval.
     */
    @Metadata(generated = true)
    public static AssistantToolsRetrieval fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();

                reader.skipChildren();
            }
            return new AssistantToolsRetrieval();
        });
    }
}
