// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.openai.models;

/**
 * Defines values for ChatCompletionRequestMessageContentPartImageDetail.
 */
public enum ChatCompletionRequestMessageContentPartImageDetail {
    /**
     * Enum value auto.
     */
    AUTO("auto"),

    /**
     * Enum value low.
     */
    LOW("low"),

    /**
     * Enum value high.
     */
    HIGH("high");

    /**
     * The actual serialized value for a ChatCompletionRequestMessageContentPartImageDetail instance.
     */
    private final String value;

    ChatCompletionRequestMessageContentPartImageDetail(String value) {
        this.value = value;
    }

    /**
     * Parses a serialized value to a ChatCompletionRequestMessageContentPartImageDetail instance.
     * 
     * @param value the serialized value to parse.
     * @return the parsed ChatCompletionRequestMessageContentPartImageDetail object, or null if unable to parse.
     */
    public static ChatCompletionRequestMessageContentPartImageDetail fromString(String value) {
        if (value == null) {
            return null;
        }
        ChatCompletionRequestMessageContentPartImageDetail[] items
            = ChatCompletionRequestMessageContentPartImageDetail.values();
        for (ChatCompletionRequestMessageContentPartImageDetail item : items) {
            if (item.toString().equalsIgnoreCase(value)) {
                return item;
            }
        }
        return null;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String toString() {
        return this.value;
    }
}
