// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.openai.models;

/**
 * Defines values for Code1.
 */
public enum Code1 {
    /**
     * Enum value server_error.
     */
    SERVER_ERROR("server_error"),

    /**
     * Enum value rate_limit_exceeded.
     */
    RATE_LIMIT_EXCEEDED("rate_limit_exceeded");

    /**
     * The actual serialized value for a Code1 instance.
     */
    private final String value;

    Code1(String value) {
        this.value = value;
    }

    /**
     * Parses a serialized value to a Code1 instance.
     * 
     * @param value the serialized value to parse.
     * @return the parsed Code1 object, or null if unable to parse.
     */
    public static Code1 fromString(String value) {
        if (value == null) {
            return null;
        }
        Code1[] items = Code1.values();
        for (Code1 item : items) {
            if (item.toString().equalsIgnoreCase(value)) {
                return item;
            }
        }
        return null;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String toString() {
        return this.value;
    }
}
