// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.openai.models;

/**
 * Defines values for Code.
 */
public enum Code {
    /**
     * Enum value server_error.
     */
    SERVER_ERROR("server_error"),

    /**
     * Enum value rate_limit_exceeded.
     */
    RATE_LIMIT_EXCEEDED("rate_limit_exceeded"),

    /**
     * Enum value invalid_prompt.
     */
    INVALID_PROMPT("invalid_prompt");

    /**
     * The actual serialized value for a Code instance.
     */
    private final String value;

    Code(String value) {
        this.value = value;
    }

    /**
     * Parses a serialized value to a Code instance.
     * 
     * @param value the serialized value to parse.
     * @return the parsed Code object, or null if unable to parse.
     */
    public static Code fromString(String value) {
        if (value == null) {
            return null;
        }
        Code[] items = Code.values();
        for (Code item : items) {
            if (item.toString().equalsIgnoreCase(value)) {
                return item;
            }
        }
        return null;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String toString() {
        return this.value;
    }
}
