// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.openai.models;

import io.clientcore.core.annotation.Metadata;
import io.clientcore.core.util.ExpandableEnum;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Defines values for CreateChatCompletionRequestModel.
 */
public final class CreateChatCompletionRequestModel implements ExpandableEnum<String> {
    private static final Map<String, CreateChatCompletionRequestModel> VALUES = new ConcurrentHashMap<>();

    /**
     * Static value gpt-4-0125-preview for CreateChatCompletionRequestModel.
     */
    @Metadata(generated = true)
    public static final CreateChatCompletionRequestModel GPT_4_0125_PREVIEW = fromString("gpt-4-0125-preview");

    /**
     * Static value gpt-4-turbo-preview for CreateChatCompletionRequestModel.
     */
    @Metadata(generated = true)
    public static final CreateChatCompletionRequestModel GPT_4_TURBO_PREVIEW = fromString("gpt-4-turbo-preview");

    /**
     * Static value gpt-4-1106-preview for CreateChatCompletionRequestModel.
     */
    @Metadata(generated = true)
    public static final CreateChatCompletionRequestModel GPT_4_1106_PREVIEW = fromString("gpt-4-1106-preview");

    /**
     * Static value gpt-4-vision-preview for CreateChatCompletionRequestModel.
     */
    @Metadata(generated = true)
    public static final CreateChatCompletionRequestModel GPT_4_VISION_PREVIEW = fromString("gpt-4-vision-preview");

    /**
     * Static value gpt-4 for CreateChatCompletionRequestModel.
     */
    @Metadata(generated = true)
    public static final CreateChatCompletionRequestModel GPT_4 = fromString("gpt-4");

    /**
     * Static value gpt-4-0314 for CreateChatCompletionRequestModel.
     */
    @Metadata(generated = true)
    public static final CreateChatCompletionRequestModel GPT_4_0314 = fromString("gpt-4-0314");

    /**
     * Static value gpt-4-0613 for CreateChatCompletionRequestModel.
     */
    @Metadata(generated = true)
    public static final CreateChatCompletionRequestModel GPT_4_0613 = fromString("gpt-4-0613");

    /**
     * Static value gpt-4-32k for CreateChatCompletionRequestModel.
     */
    @Metadata(generated = true)
    public static final CreateChatCompletionRequestModel GPT_4_32K = fromString("gpt-4-32k");

    /**
     * Static value gpt-4-32k-0314 for CreateChatCompletionRequestModel.
     */
    @Metadata(generated = true)
    public static final CreateChatCompletionRequestModel GPT_4_32K_0314 = fromString("gpt-4-32k-0314");

    /**
     * Static value gpt-4-32k-0613 for CreateChatCompletionRequestModel.
     */
    @Metadata(generated = true)
    public static final CreateChatCompletionRequestModel GPT_4_32K_0613 = fromString("gpt-4-32k-0613");

    /**
     * Static value gpt-3.5-turbo for CreateChatCompletionRequestModel.
     */
    @Metadata(generated = true)
    public static final CreateChatCompletionRequestModel GPT_3_5_TURBO = fromString("gpt-3.5-turbo");

    /**
     * Static value gpt-3.5-turbo-16k for CreateChatCompletionRequestModel.
     */
    @Metadata(generated = true)
    public static final CreateChatCompletionRequestModel GPT_3_5_TURBO_16K = fromString("gpt-3.5-turbo-16k");

    /**
     * Static value gpt-3.5-turbo-0301 for CreateChatCompletionRequestModel.
     */
    @Metadata(generated = true)
    public static final CreateChatCompletionRequestModel GPT_3_5_TURBO_0301 = fromString("gpt-3.5-turbo-0301");

    /**
     * Static value gpt-3.5-turbo-0613 for CreateChatCompletionRequestModel.
     */
    @Metadata(generated = true)
    public static final CreateChatCompletionRequestModel GPT_3_5_TURBO_0613 = fromString("gpt-3.5-turbo-0613");

    /**
     * Static value gpt-3.5-turbo-1106 for CreateChatCompletionRequestModel.
     */
    @Metadata(generated = true)
    public static final CreateChatCompletionRequestModel GPT_3_5_TURBO_1106 = fromString("gpt-3.5-turbo-1106");

    /**
     * Static value gpt-3.5-turbo-0125 for CreateChatCompletionRequestModel.
     */
    @Metadata(generated = true)
    public static final CreateChatCompletionRequestModel GPT_3_5_TURBO_0125 = fromString("gpt-3.5-turbo-0125");

    /**
     * Static value gpt-3.5-turbo-16k-0613 for CreateChatCompletionRequestModel.
     */
    @Metadata(generated = true)
    public static final CreateChatCompletionRequestModel GPT_3_5_TURBO_16K_0613 = fromString("gpt-3.5-turbo-16k-0613");

    private final String name;

    private CreateChatCompletionRequestModel(String name) {
        this.name = name;
    }

    /**
     * Creates or finds a CreateChatCompletionRequestModel.
     * 
     * @param name a name to look for.
     * @return the corresponding CreateChatCompletionRequestModel.
     */
    @Metadata(generated = true)
    public static CreateChatCompletionRequestModel fromString(String name) {
        if (name == null) {
            return null;
        }
        CreateChatCompletionRequestModel value = VALUES.get(name);
        if (value != null) {
            return value;
        }
        return VALUES.computeIfAbsent(name, key -> new CreateChatCompletionRequestModel(key));
    }

    /**
     * Gets the value of the CreateChatCompletionRequestModel instance.
     * 
     * @return the value of the CreateChatCompletionRequestModel instance.
     */
    @Metadata(generated = true)
    @Override
    public String getValue() {
        return this.name;
    }

    @Metadata(generated = true)
    @Override
    public String toString() {
        return name;
    }
}
