// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.openai.models;

import io.clientcore.core.annotation.Metadata;
import io.clientcore.core.annotation.TypeConditions;
import io.clientcore.core.json.JsonReader;
import io.clientcore.core.json.JsonSerializable;
import io.clientcore.core.json.JsonToken;
import io.clientcore.core.json.JsonWriter;
import java.io.IOException;
import java.util.List;

/**
 * The SubmitToolOutputs model.
 */
@Metadata(conditions = { TypeConditions.IMMUTABLE })
public final class SubmitToolOutputs implements JsonSerializable<SubmitToolOutputs> {
    /*
     * A list of the relevant tool calls.
     */
    @Metadata(generated = true)
    private final List<RunToolCallObject> toolCalls;

    /**
     * Creates an instance of SubmitToolOutputs class.
     * 
     * @param toolCalls the toolCalls value to set.
     */
    @Metadata(generated = true)
    private SubmitToolOutputs(List<RunToolCallObject> toolCalls) {
        this.toolCalls = toolCalls;
    }

    /**
     * Get the toolCalls property: A list of the relevant tool calls.
     * 
     * @return the toolCalls value.
     */
    @Metadata(generated = true)
    public List<RunToolCallObject> getToolCalls() {
        return this.toolCalls;
    }

    /**
     * {@inheritDoc}
     */
    @Metadata(generated = true)
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeArrayField("tool_calls", this.toolCalls, (writer, element) -> writer.writeJson(element));
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of SubmitToolOutputs from the JsonReader.
     * 
     * @param jsonReader The JsonReader being read.
     * @return An instance of SubmitToolOutputs if the JsonReader was pointing to an instance of it, or null if it was
     * pointing to JSON null.
     * @throws IllegalStateException If the deserialized JSON object was missing any required properties.
     * @throws IOException If an error occurs while reading the SubmitToolOutputs.
     */
    @Metadata(generated = true)
    public static SubmitToolOutputs fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            List<RunToolCallObject> toolCalls = null;
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();

                if ("tool_calls".equals(fieldName)) {
                    toolCalls = reader.readArray(reader1 -> RunToolCallObject.fromJson(reader1));
                } else {
                    reader.skipChildren();
                }
            }
            return new SubmitToolOutputs(toolCalls);
        });
    }
}
